### ISSUE TITLE
Investigate hosts running out of memory due to Beacon nodes

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-nimbus#12]
We've been seeing Nimbus hosts failing due to lack of memory, like yesterday:
![nimbus_master_no_mem](https://user-images.githubusercontent.com/2212681/77634570-7689d500-6f51-11ea-95d6-60f62db2cb96.png)
https://grafana.status.im/d/QCTZ8-Vmk/single-host?orgId=1&var-host=master-01.aws-eu-central-1a.nimbus.test&from=1585134265851&to=1585216675067

**Comment by jakubgs** [comment]
Ah, I see, we currently don't have any memory limits set on the containers:
https://github.com/status-im/infra-role-beacon-node/blob/2923405a9d93d5015acb65d325122c2f8baba7ee/tasks/container.yml#L14-L35

We could use the `resources` block in Docker Compose configuration to set limits:
https://docs.docker.com/compose/compose-file/#resources
```yaml
version: "3.7"
services:
  redis:
    image: redis:alpine
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
```
In order to avoid killing the host by killing the container when it hits the limit.

**Comment by zah** [comment]
Restarting the container would be an appropriate action. The beacon nodes
should be able to rejoin the network and continue.

**Comment by jakubgs** [comment]
Here's changes to the role: https://github.com/status-im/infra-role-beacon-node/commit/eb798800
And here's the config change I deployed to all the hosts: 0e184b9e96d85259320d7d49bc562fa1b52bbdf9

Result on `master-01.aws-eu-central-1a.nimbus.test`:
```
 % cat /docker/beacon-node-testnet1-2/docker-compose.yml | grep -A 6 resources
            resources:
                limits:
                    cpus: '0.2'
                    memory: 779M
                reservations:
                    cpus: '0.1'
                    memory: 389M
```
Current memory limits are calculated based on available memory:
https://github.com/status-im/infra-nimbus/blob/0e184b9e96d85259320d7d49bc562fa1b52bbdf9/ansible/group_vars/nimbus-slaves.yml#L11-L15
I'm using `0.20` as upper limit for both CPU and memory to leave 20% of OS even when all containers have saturated their available resources. We can adjust that later if needed.

**Comment by jakubgs** [comment]
I also decided to add an explicit restart policy: https://github.com/status-im/infra-role-beacon-node/commit/a85f7e90

So now it should attempt to restart the container 3 times with delay of 10 seconds on failure:
```
 % cd /docker/beacon-node-testnet0-1                                              
 % cat docker-compose.yml | grep -A 4 restart_policy
            restart_policy:
                condition: on-failure
                delay: 10s
                max_attempts: 3
                window: 120
```
The `on-failure` condition should also cover failure due to running out of memory.
This usually shows up as [`137` exit code](https://success.docker.com/article/what-causes-a-container-to-exit-with-code-137) caused by out-of-memory error.
