### ISSUE TITLE
Mandatory RocketPool upgrade is coming

### ISSUE THREAD

**Issue by zah** [status-im/infra-nimbus#123]
We need to upgrade our RocketPool nodes to the latest version of the RockerPool smart node software before 15th of August:

https://medium.com/@darrenlangley/7a4ea45df09c

**Comment by jakubgs** [comment]
Indeed, there is a `1.5.0` release available: https://github.com/rocket-pool/smartnode-install/releases/tag/v1.5.0

And they state:

>This is a very high priority update for all users on the Prater Testnet; it has required support for The Goerli-Prater Merge, currently expected in the 2nd week of August.

And they have an upgrade guide for different setups, including Docker:
https://docs.rocketpool.net/guides/redstone/docker-migration.html

**Comment by jakubgs** [comment]
And of course:

>The Merge requires you to run your own Execution client, so you won't be able to use light clients like Infura or Pocket anymore. v1.5.0 won't have them anymore, and won't let you start the stack until you select a full Execution client.
>
>Because of this change, you should switch to a full client while you're still on v1.4, let it sync to completion, and then upgrade to v1.5.

**Comment by jakubgs** [comment]
We're also running quite old Nimbus node:
```
admin@node-01.aws-eu-central-1a.rocket.prod:~ % sudo /data/rocketpool/eth2-node/repo/build/nimbus_beacon_node --version
Nimbus beacon node v1.5.4-b1218c-stateofus
```

**Comment by jakubgs** [comment]
Okay, I see what we've used so far:
```
admin@node-01.aws-eu-central-1a.rocket.prod:/docker/rocketpool % sudo grep -A3 eth1 config.yml
  eth1:
    provider: http://mainnet-01.aws-eu-central-1a.nimbus.geth.wg:8545
    wsProvider: ws://mainnet-01.aws-eu-central-1a.nimbus.geth.wg:8546
    mainnetProvider: http://mainnet-01.aws-eu-central-1a.nimbus.geth.wg:8545
```
I guess we'll need a dedicated node for Rocketpool.
