### ISSUE TITLE
Configure IPv6 addresses for Nimbus nodes

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-nimbus#176]
Based on request from @arnetheduck we need to add IPv6 addresses to Nimbus hosts.

I have already opened a ticket with InnovaHosting:
https://client.innovahosting.net/viewticket.php?tid=769921&c=UeLgmsq7

**Comment by jakubgs** [comment]
We got an IPv6 range from InnovaHosting to use, I requested 512 addresses for now:

|||
|-|-|
| Network	| `2a0a:d580:40:60::/64` |
| Gateway | `2a0a:d580:40:60::1` |
| Start | `2a0a:d580:40:60::100` |
| End | `2a0a:d580:40:60::2ff` |

One issue with this tho is that Innova doesn't provide IPs via DHCP but with static configuration:
```
jakubgs@geth-01.ih-eu-mda1.nimbus.holesky:~ % sudo cat /etc/netplan/00-installer-config.yaml
# This is the network config written by 'subiquity'
network:
  ethernets:
    eno1:
      addresses: [ 194.33.40.71/24 ]
      gateway4: 194.33.40.1
      nameservers:
        addresses: [ 194.33.40.10, 1.1.1.1 ]
  version: 2
```

**Comment by jakubgs** [comment]
Wrote a small utility to generate and validate IPv6 ranges:

- [`infra-utils#084cfbba`](https://github.com/status-im/infra-utils/commit/084cfbba) - network/ipv6gen.py: tool for generating ipv6 ranges

Mostly as a way to familiarize myself with it.
```
 > ./network/ipv6gen.py --network F00D:CAFE::/64 --start F00D:CAFE::15 --end F00D:CAFE::1f --count 20 
Network: f00d:cafe::/64
Start: f00d:cafe::15
End: f00d:cafe::1f
Count: 20

f00d:cafe::15
f00d:cafe::16
f00d:cafe::17
f00d:cafe::18
f00d:cafe::19
f00d:cafe::1a
f00d:cafe::1b
f00d:cafe::1c
f00d:cafe::1d
f00d:cafe::1e
Address beyond range: f00d:cafe::1f
```

**Comment by jakubgs** [comment]
I've enable IPv6 for our AWS VPC and subnet:

- [`infra-tf-aws-vpc#1057a690`](https://github.com/status-im/infra-tf-aws-vpc/commit/1057a690) - enable IPv6 addresses on VPC and subnet
- [`infra-tf-aws-vpc#f29a70c7`](https://github.com/status-im/infra-tf-aws-vpc/commit/f29a70c7) - upgrade provider from 4.67.0 to 5.40.0
- [`infra-tf-aws-vpc#229bbe68`](https://github.com/status-im/infra-tf-aws-vpc/commit/229bbe68) - allow public access to IPv6 addresses

But it appears that's not enough.

**Comment by jakubgs** [comment]
Some relevant links:

- https://docs.aws.amazon.com/whitepapers/latest/ipv6-on-aws/amazon-vpc-internet-access.html
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-instance-addressing.html#assign-ipv6-address
- https://medium.com/@mattias.holmlund/setting-up-ipv6-on-amazon-with-terraform-e14b3bfef577
- https://colinbarker.me.uk/blog/2023-02-11-enabling-ipv6-on-aws-using-terraform/

**Comment by jakubgs** [comment]
This is kinda dumb, Terraform doesn't know how to assign the IP without re-creating the instance:

![image](https://github.com/status-im/infra-nimbus/assets/2212681/a51e7c12-82bf-4d65-87ef-a6edefd4727c)

But it can be easily done via the Web UI:

![image](https://github.com/status-im/infra-nimbus/assets/2212681/2a3db77b-b890-45a2-afa5-84115eab21c1)

**Comment by jakubgs** [comment]
Relevant changes in AWS instance role:

- [`infra-tf-amazon-web-services#4ed017e4`](https://github.com/status-im/infra-tf-amazon-web-services/commit/4ed017e4) - add IPv6 address to all EC2 instances
- [`infra-tf-amazon-web-services#03fde5eb`](https://github.com/status-im/infra-tf-amazon-web-services/commit/03fde5eb) - upgrade provider from 4.67.0 to 5.40.0
- [`infra-tf-amazon-web-services#d012d2e7`](https://github.com/status-im/infra-tf-amazon-web-services/commit/d012d2e7) - add public_ips_v6 to outputs
- [`infra-tf-amazon-web-services#f53902ea`](https://github.com/status-im/infra-tf-amazon-web-services/commit/f53902ea) - add CloudFlare AAAA record for IPv6 address

And now we can reach it via `nmap`(ICMP is not enabled in security groups):
```
jakubgs@geth-01.ih-eu-mda1.nimbus.holesky:~ % nmap -6 -Pn -p22,9100 bootstrap-01.aws-eu-central-1a.nimbus.mainnet.statusim.net
Starting Nmap 7.80 ( https://nmap.org ) at 2024-03-14 15:16 UTC
Nmap scan report for bootstrap-01.aws-eu-central-1a.nimbus.mainnet.statusim.net (2a05:d014:113c:2400:6e6f:d115:b30c:9a12)
Host is up (0.034s latency).
Other addresses for bootstrap-01.aws-eu-central-1a.nimbus.mainnet.statusim.net (not scanned): 3.120.104.18

PORT     STATE  SERVICE
22/tcp   open   ssh
9100/tcp closed jetdirect
```

**Comment by jakubgs** [comment]
For InnovaHosting I'm not sure how I want to do it. Managing static IPs with `bootstrap` Ansible role just for ~50 hosts from Innova seems kinda overkill. But at the same time, we do need a place to store those IPv6 addresses and their mappings to hosts.

**Comment by jakubgs** [comment]
Added IPv6 to Consul advertised addresses at bootstrapping time:

- [`infra-role-bootstrap-linux#aaad7e7b`](https://github.com/status-im/infra-role-bootstrap-linux/commit/aaad7e7b) - consul: add IPv4 and IPv6 to advertised addresses

We can also in the future use the addresses in Beacon node ansible role.

**Comment by jakubgs** [comment]
Adding it manually on InnovaHosts definitely works:
```
jakubgs@geth-01.ih-eu-mda1.nimbus.holesky:~ % sudo cat /etc/netplan/00-installer-config.yaml
# This is the network config written by 'subiquity'
network:
  ethernets:
    eno1:
      addresses:
        - 194.33.40.71/24
        - 2a0a:d580:40:60::100/64
      gateway4: 194.33.40.1
      gateway6: 2a0a:d580:40:60::1
      nameservers:
        addresses: [ 194.33.40.10, 1.1.1.1 ]
  version: 2
```
It is reachable:
```
jakubgs@bootstrap-01.aws-eu-central-1a.nimbus.mainnet:~ % ping -c4 2a0a:d580:40:60::100
PING 2a0a:d580:40:60::100(2a0a:d580:40:60::100) 56 data bytes
64 bytes from 2a0a:d580:40:60::100: icmp_seq=1 ttl=55 time=34.6 ms
64 bytes from 2a0a:d580:40:60::100: icmp_seq=2 ttl=55 time=34.6 ms
64 bytes from 2a0a:d580:40:60::100: icmp_seq=3 ttl=55 time=34.6 ms
64 bytes from 2a0a:d580:40:60::100: icmp_seq=4 ttl=55 time=34.9 ms

--- 2a0a:d580:40:60::100 ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 3005ms
rtt min/avg/max/mdev = 34.567/34.677/34.922/0.144 ms
```
