### ISSUE TITLE
Update hive and add notification

### ISSUE THREAD

**Issue by advaita-saha** [status-im/infra-nimbus#245]
## Hive Update
hive updates have been merged, but this now creates a new way of feeding client data
which is `--client-file` <a-yaml-file>

example format of the file
```yaml
- client: nimbus-el
  dockerfile: git
  build_args:
    tag: master
```

So for the nightly run we would utilise the pre-build images and the yaml file to generate would look something like 
```yaml
- client: nimbus-el
  dockerfile:
  build_args:
    tag: master
```

For the manual runs we need to get in an additional parameter from the user in jenkins which would be `dockerfile` type which can be either `git` or empty. The `tag` in this file is the branch 
looking like
```yaml
- client: nimbus-el
  dockerfile: 
  build_args:
    tag: master
```

For a 2 client run for example the `ethereum/sync` run, the file would look something like this 
```yaml
- client: nimbus-el
  dockerfile: 
  build_args:
    tag: master
- client: reth
```

## Notifications
Since hive runs are stable now, this is one of the major goals of hive is to detect regressions as we keep developing `nimbus-eth1`. Now we have all the results posted at https://hive.nimbus.team but we often might overlook being busy with other stuff
An ideal thing would be to track differences in test case passing and issue a notification in discord 
Example of a recent regression detected by hive 
<img width="1743" alt="Image" src="https://github.com/user-attachments/assets/253f9e82-9faf-42c4-8c6d-e350f219eade" />
