### ISSUE TITLE
Migrate whole Pyrmont fleet to Hetzner

### ISSUE THREAD

**Issue by jakubgs** [status-im/infra-nimbus#65]
The Pyrmont fleet has little utility but has to exist until Ethereum Foundation decides it doesn't need it anymore.

Considering the costs - ~6k EUR per month - we need to move out validators to more cost effective AX41-NVMe Hetzner hosts.
This should reduce the cost of the fleet 30x fold easily. The layout suggested by @zah looks like this:

* `metal-01` - 4000 validators per instance
* `metal-02` - 989 validators per instance
* `metal-03`- 10 validators per instance
* `metal-04` - 1 validator per instance

This assumes 4 beacon node instances per host: `stable`, `testing`, `unstable`, and `nim-libp2p-auto-bump-unstable`

Depending on whether a single host can handle 4 instances running 4000 validators each I might have to redesign this layout.

**Comment by jakubgs** [comment]
I have ordered 4 `AX41-NVMe` hosts in `hel1`. According to docs they should arrive in one day:

![image](https://user-images.githubusercontent.com/2212681/125748276-a9f006c2-543d-4938-8da6-0c701dc33625.png)

https://docs.hetzner.com/general/others/order-processing/

**Comment by jakubgs** [comment]
Oh wow, already deployed:

![image](https://user-images.githubusercontent.com/2212681/125759744-89f43160-665c-4441-9ce8-65394194520a.png)

**Comment by arnetheduck** [comment]
> The Prater fleet has little utility but has to exist until Ethereum Foundation decides it doesn't need it anymore.

Assuming you mean pyrmont, the idea here is that it will be used to test the altair hard fork then a few weeks after that it will be shut down in favor of Prater that is the "new" long-running testnet.

**Comment by jakubgs** [comment]
Yes, I meant Pyrmont. Fixed.

**Comment by jakubgs** [comment]
I've added the new `metal` hosts to the inventory: https://github.com/status-im/infra-nimbus/commit/df96f214

**Comment by jakubgs** [comment]
I've bootstrapped all 4 hosts, for now I'll just deploy beacon nodes without validators to see how they behave:
```
 > a nimbus-pyrmont-metal -o -a 'uname -v'
metal-01.he-eu-hel1.nimbus.pyrmont | CHANGED | rc=0 | (stdout) #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021
metal-02.he-eu-hel1.nimbus.pyrmont | CHANGED | rc=0 | (stdout) #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021
metal-03.he-eu-hel1.nimbus.pyrmont | CHANGED | rc=0 | (stdout) #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021
metal-04.he-eu-hel1.nimbus.pyrmont | CHANGED | rc=0 | (stdout) #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021
```

**Comment by jakubgs** [comment]
Deployed, we'll see tomorrow how they behave:
```
 > a nimbus-pyrmont-metal -a "sudo systemctl list-units 'beacon-node*' | head -n4"
metal-01.he-eu-hel1.nimbus.pyrmont | CHANGED | rc=0 >>
  UNIT                                     LOAD   ACTIVE SUB     DESCRIPTION                                     
  beacon-node-pyrmont-stable.service       loaded active running Nimbus Beacon Node on pyrmont network (stable)  
  beacon-node-pyrmont-testing.service      loaded active running Nimbus Beacon Node on pyrmont network (testing) 
  beacon-node-pyrmont-unstable.service     loaded active running Nimbus Beacon Node on pyrmont network (unstable)
metal-04.he-eu-hel1.nimbus.pyrmont | CHANGED | rc=0 >>
  UNIT                                     LOAD   ACTIVE SUB     DESCRIPTION                                     
  beacon-node-pyrmont-stable.service       loaded active running Nimbus Beacon Node on pyrmont network (stable)  
  beacon-node-pyrmont-testing.service      loaded active running Nimbus Beacon Node on pyrmont network (testing) 
  beacon-node-pyrmont-unstable.service     loaded active running Nimbus Beacon Node on pyrmont network (unstable)
metal-02.he-eu-hel1.nimbus.pyrmont | CHANGED | rc=0 >>
  UNIT                                     LOAD   ACTIVE SUB     DESCRIPTION                                     
  beacon-node-pyrmont-stable.service       loaded active running Nimbus Beacon Node on pyrmont network (stable)  
  beacon-node-pyrmont-testing.service      loaded active running Nimbus Beacon Node on pyrmont network (testing) 
  beacon-node-pyrmont-unstable.service     loaded active running Nimbus Beacon Node on pyrmont network (unstable)
metal-03.he-eu-hel1.nimbus.pyrmont | CHANGED | rc=0 >>
  UNIT                                     LOAD   ACTIVE SUB     DESCRIPTION                                     
  beacon-node-pyrmont-stable.service       loaded active running Nimbus Beacon Node on pyrmont network (stable)  
  beacon-node-pyrmont-testing.service      loaded active running Nimbus Beacon Node on pyrmont network (testing) 
  beacon-node-pyrmont-unstable.service     loaded active running Nimbus Beacon Node on pyrmont network (unstable)
```
Change: https://github.com/status-im/infra-nimbus/commit/87d23f8f

**Comment by jakubgs** [comment]
I've prepared the new layout:
```yaml
validators_layout:
  "metal-01.he-eu-hel1.nimbus.pyrmont": # 4000 validators each
    "stable":   { start: 0,     end:  4000 }
    "unstable": { start: 4000,  end:  8000 }
    "testing":  { start: 8000,  end: 12000 }
    "libp2p":   { start: 12000, end: 16000 }
  "metal-02.he-eu-hel1.nimbus.pyrmont": # 989  validators each
    "stable":   { start: 16000, end: 16989 }
    "unstable": { start: 16989, end: 17978 }
    "testing":  { start: 17978, end: 18967 }
    "libp2p":   { start: 18967, end: 19956 }
  "metal-03.he-eu-hel1.nimbus.pyrmont": # 10 validators each
    "stable":   { start: 19956, end: 19966 }
    "unstable": { start: 19966, end: 19976 }
    "testing":  { start: 19976, end: 19986 }
    "libp2p":   { start: 19986, end: 19996 }
  "metal-04.he-eu-hel1.nimbus.pyrmont": # 2 validators each
    "stable":   { start: 19996, end: 19997 }
    "unstable": { start: 19997, end: 19998 }
    "testing":  { start: 19998, end: 19999 }
    "libp2p":   { start: 19999, end: 20000 }
```
I will destroy all containers on the old AWS hosts and deploy the validators to the Hetzner hosts.
